Traceback (most recent call last):
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/oscar/core/loading.py", line 244, in get_model
    return apps.get_model(app_label, model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 141, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/multistore/manage.py", line 22, in <module>
    main()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/multistore/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/multistore/merchant_apps/store/voucher/models.py", line 12, in <module>
    OscarVoucher = get_model('voucher', 'Voucher') 
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/oscar/core/loading.py", line 259, in get_model
    return apps.get_registered_model(app_label, model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 273, in get_registered_model
    raise LookupError(
LookupError: Model 'voucher.Voucher' not registered.
Traceback (most recent call last):
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/oscar/core/loading.py", line 244, in get_model
    return apps.get_model(app_label, model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 141, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/multistore/manage.py", line 22, in <module>
    main()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/multistore/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/multistore/merchant_apps/store/voucher/models.py", line 12, in <module>
    OscarVoucher = get_model('voucher', 'Voucher') 
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/oscar/core/loading.py", line 259, in get_model
    return apps.get_registered_model(app_label, model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 273, in get_registered_model
    raise LookupError(
LookupError: Model 'voucher.Voucher' not registered.
Traceback (most recent call last):
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/oscar/core/loading.py", line 244, in get_model
    return apps.get_model(app_label, model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 141, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/multistore/manage.py", line 22, in <module>
    main()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/multistore/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/multistore/merchant_apps/store/voucher/models.py", line 12, in <module>
    OscarVoucher = get_model('voucher', 'Voucher') 
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/oscar/core/loading.py", line 259, in get_model
    return apps.get_registered_model(app_label, model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 273, in get_registered_model
    raise LookupError(
LookupError: Model 'voucher.Voucher' not registered.
Traceback (most recent call last):
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/oscar/core/loading.py", line 244, in get_model
    return apps.get_model(app_label, model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 141, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/multistore/manage.py", line 22, in <module>
    main()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/multistore/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/multistore/merchant_apps/store/voucher/models.py", line 12, in <module>
    OscarVoucher = get_model('voucher', 'Voucher') 
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/oscar/core/loading.py", line 259, in get_model
    return apps.get_registered_model(app_label, model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 273, in get_registered_model
    raise LookupError(
LookupError: Model 'voucher.Voucher' not registered.
Traceback (most recent call last):
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/oscar/core/loading.py", line 244, in get_model
    return apps.get_model(app_label, model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 141, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/multistore/manage.py", line 22, in <module>
    main()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/multistore/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/multistore/merchant_apps/store/voucher/models.py", line 12, in <module>
    OscarVoucher = get_model('voucher', 'Voucher') 
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/oscar/core/loading.py", line 259, in get_model
    return apps.get_registered_model(app_label, model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 273, in get_registered_model
    raise LookupError(
LookupError: Model 'voucher.Voucher' not registered.
Traceback (most recent call last):
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/oscar/core/loading.py", line 244, in get_model
    return apps.get_model(app_label, model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 141, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/multistore/manage.py", line 22, in <module>
    main()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/multistore/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/multistore/merchant_apps/store/voucher/models.py", line 12, in <module>
    OscarVoucher = get_model('voucher', 'Voucher') 
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/oscar/core/loading.py", line 259, in get_model
    return apps.get_registered_model(app_label, model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jillo/Documents/Projects/ Multitentant-Ecommerce-System-Backend/venv/lib/python3.12/site-packages/django/apps/registry.py", line 273, in get_registered_model
    raise LookupError(
LookupError: Model 'voucher.Voucher' not registered.
                                                                                                                                                                 
┌──(venv)─(jillo㉿kali)-[~/Documents/Projects/ Multitentant-Ecommerce-System-Backend/multistore]
└─$ 